/**
 * Major fiat→crypto payout targets shown in UI + validated on-chain formats (fiatToCryptoTransfer).
 * Tickers are verified against Coinbase `/v2/exchange-rates` for USD/EUR so indicative quotes resolve.
 */

/** Canonical payout rail identifiers — match validators in fiatToCryptoTransfer.js */
export const CRYPTO_TRANSFER_NETWORK_ID = Object.freeze({
    BITCOIN_MAINNET: "bitcoin_mainnet",
    ETHEREUM_MAINNET: "ethereum_mainnet",
    SOLANA_MAINNET: "solana_mainnet",
    LITECOIN_MAINNET: "litecoin_mainnet",
    DOGECOIN_MAINNET: "dogecoin_mainnet",
    RIPPLE_MAINNET: "ripple_mainnet",
    CARDANO_MAINNET: "cardano_mainnet",
    COSMOS_FAMILY_MAINNET: "cosmos_family_mainnet",
    POLKADOT_MAINNET: "polkadot_mainnet",
    BITCOIN_CASH_MAINNET: "bitcoin_cash_mainnet",
    NEAR_MAINNET: "near_mainnet",
    FILECOIN_MAINNET: "filecoin_mainnet",
    HEX64_ACCOUNT_MAINNET: "hex64_account_mainnet",
    EOS_MAINNET: "eos_mainnet",
    TEZOS_MAINNET: "tezos_mainnet",
    STELLAR_MAINNET: "stellar_mainnet",
    ZCASH_MAINNET: "zcash_mainnet",
    HEDERA_MAINNET: "hedera_mainnet",
    STACKS_MAINNET: "stacks_mainnet",
    TON_MAINNET: "ton_mainnet",
});

const N = CRYPTO_TRANSFER_NETWORK_ID;

/**
 * Primary withdrawal network we validate against (one per asset).
 * ERC-20–style majors use Ethereum mainnet; multi-chain tokens (e.g. USDT) default to Ethereum here.
 *
 * @type {Readonly<Record<string, string>>}
 */
export const ASSET_PRIMARY_NETWORK = Object.freeze({
    BTC: N.BITCOIN_MAINNET,
    ETH: N.ETHEREUM_MAINNET,
    USDT: N.ETHEREUM_MAINNET,
    USDC: N.ETHEREUM_MAINNET,
    SOL: N.SOLANA_MAINNET,
    XRP: N.RIPPLE_MAINNET,
    ADA: N.CARDANO_MAINNET,
    DOGE: N.DOGECOIN_MAINNET,
    LINK: N.ETHEREUM_MAINNET,
    DOT: N.POLKADOT_MAINNET,
    MATIC: N.ETHEREUM_MAINNET,
    SHIB: N.ETHEREUM_MAINNET,
    AVAX: N.ETHEREUM_MAINNET,
    TON: N.TON_MAINNET,
    UNI: N.ETHEREUM_MAINNET,
    ATOM: N.COSMOS_FAMILY_MAINNET,
    LTC: N.LITECOIN_MAINNET,
    BCH: N.BITCOIN_CASH_MAINNET,
    NEAR: N.NEAR_MAINNET,
    FIL: N.FILECOIN_MAINNET,
    APT: N.HEX64_ACCOUNT_MAINNET,
    ARB: N.ETHEREUM_MAINNET,
    OP: N.ETHEREUM_MAINNET,
    AAVE: N.ETHEREUM_MAINNET,
    MKR: N.ETHEREUM_MAINNET,
    SNX: N.ETHEREUM_MAINNET,
    CRV: N.ETHEREUM_MAINNET,
    COMP: N.ETHEREUM_MAINNET,
    GRT: N.ETHEREUM_MAINNET,
    MANA: N.ETHEREUM_MAINNET,
    SAND: N.ETHEREUM_MAINNET,
    EOS: N.EOS_MAINNET,
    XTZ: N.TEZOS_MAINNET,
    XLM: N.STELLAR_MAINNET,
    BAT: N.ETHEREUM_MAINNET,
    ZEC: N.ZCASH_MAINNET,
    HBAR: N.HEDERA_MAINNET,
    INJ: N.COSMOS_FAMILY_MAINNET,
    RNDR: N.ETHEREUM_MAINNET,
    STX: N.STACKS_MAINNET,
    IMX: N.ETHEREUM_MAINNET,
    LDO: N.ETHEREUM_MAINNET,
    PEPE: N.ETHEREUM_MAINNET,
    FET: N.ETHEREUM_MAINNET,
    WLD: N.ETHEREUM_MAINNET,
    TIA: N.COSMOS_FAMILY_MAINNET,
    SEI: N.COSMOS_FAMILY_MAINNET,
    SUI: N.HEX64_ACCOUNT_MAINNET,
    POL: N.ETHEREUM_MAINNET,
    WBTC: N.ETHEREUM_MAINNET,
    PYTH: N.ETHEREUM_MAINNET,
});

/** Liquid / tier‑1 ordering for dropdown (Coinbase-supported symbols above). */
export const FIAT_TO_CRYPTO_MAJOR_TARGET_ASSETS = Object.freeze([
    "BTC",
    "ETH",
    "USDT",
    "USDC",
    "SOL",
    "XRP",
    "ADA",
    "DOGE",
    "LINK",
    "DOT",
    "MATIC",
    "SHIB",
    "AVAX",
    "TON",
    "UNI",
    "ATOM",
    "LTC",
    "BCH",
    "NEAR",
    "FIL",
    "APT",
    "ARB",
    "OP",
    "AAVE",
    "MKR",
    "SNX",
    "CRV",
    "COMP",
    "GRT",
    "MANA",
    "SAND",
    "EOS",
    "XTZ",
    "XLM",
    "BAT",
    "ZEC",
    "HBAR",
    "INJ",
    "RNDR",
    "STX",
    "IMX",
    "LDO",
    "PEPE",
    "FET",
    "WLD",
    "TIA",
    "SEI",
    "SUI",
    "POL",
    "WBTC",
    "PYTH",
]);
